
import { 
  Sparkles, 
  ScanSearch, 
  RefreshCcw, 
  FileText, 
  CheckCircle, 
  Hash, 
  PenTool, 
  Type, 
  Gavel, 
  GitBranch, 
  Flame, 
  MessageSquare, 
  FileSearch, 
  Youtube, 
  Chrome,
  Mail,
  Camera,
  Video
} from "lucide-react";

export type ToolCategory = "All" | "Writing" | "Marketing" | "Analysis" | "Developer" | "Social";

export interface Tool {
  title: string;
  description: string;
  href: string;
  icon: any;
  color: string;
  bg: string;
  category: ToolCategory;
  badge?: string;
  keywords: string[];
}

export const ALL_TOOLS: Tool[] = [
  {
    title: "AI Humanizer",
    description: "Make AI-generated text undetectable and naturally human-like.",
    href: "/humanizer",
    icon: Sparkles,
    color: "text-purple-500",
    bg: "bg-purple-500/10",
    category: "Writing",
    keywords: ["ai humanizer", "bypass ai detection", "humanize text", "undetectable ai"],
  },
  {
    title: "AI Content Detector",
    description: "Analyze text to determine if it was written by AI or a human.",
    href: "/tools/ai-content-detector",
    icon: ScanSearch,
    color: "text-violet-500",
    bg: "bg-violet-500/10",
    category: "Analysis",
    keywords: ["ai detector", "chatgpt detector", "ai content checker", "ai writing detector"],
  },
  {
    title: "Paraphrasing Tool",
    description: "Rewrite text in different styles while preserving meaning.",
    href: "/tools/paraphraser",
    icon: RefreshCcw,
    color: "text-emerald-500",
    bg: "bg-emerald-500/10",
    category: "Writing",
    keywords: ["paraphraser", "text rewriter", "rephrase tool", "article spinner"],
  },
  {
    title: "Text Summarizer",
    description: "Condense long articles into clear, concise summaries.",
    href: "/tools/summarizer",
    icon: FileText,
    color: "text-blue-500",
    bg: "bg-blue-500/10",
    category: "Writing",
    keywords: ["text summarizer", "article summarizer", "summary generator", "tl;dr generator"],
  },
  {
    title: "Grammar Polisher",
    description: "Fix grammar, spelling, and punctuation with explanations.",
    href: "/tools/grammar",
    icon: CheckCircle,
    color: "text-amber-500",
    bg: "bg-amber-500/10",
    category: "Writing",
    keywords: ["grammar checker", "spell checker", "punctuation corrector", "proofreading tool"],
  },
  {
    title: "Word Counter",
    description: "Count words, characters, sentences, and reading time.",
    href: "/tools/word-counter",
    icon: Hash,
    color: "text-cyan-500",
    bg: "bg-cyan-500/10",
    category: "Writing",
    keywords: ["word counter", "character count", "sentence counter", "reading time calculator"],
  },
  {
    title: "Blog Title Generator",
    description: "Generate click-worthy blog titles that drive traffic.",
    href: "/tools/blog-title-generator",
    icon: PenTool,
    color: "text-orange-500",
    bg: "bg-orange-500/10",
    category: "Marketing",
    keywords: ["blog title generator", "headline generator", "catchy titles", "content ideas"],
  },
  {
    title: "Case Converter",
    description: "Convert text between different cases instantly.",
    href: "/tools/case-converter",
    icon: Type,
    color: "text-pink-500",
    bg: "bg-pink-500/10",
    category: "Writing",
    keywords: ["case converter", "uppercase to lowercase", "title case", "camel case"],
  },
  {
    title: "The Devil's Advocate",
    description: "A ruthless logical critique of your arguments and ideas. Not for the faint of heart.",
    href: "/tools/devils-advocate",
    icon: Gavel,
    color: "text-zinc-500",
    bg: "bg-zinc-500/10",
    category: "Analysis",
    badge: "New",
    keywords: ["argument critique", "logical fallacy checker", "debate partner", "critical thinking"],
  },
  {
    title: "Repo Visualizer",
    description: "Understand any codebase instantly with interactive node graphs.",
    href: "/tools/github-repo-visualizer",
    icon: GitBranch,
    color: "text-emerald-500",
    bg: "bg-emerald-500/10",
    category: "Developer",
    badge: "Beta",
    keywords: ["github visualizer", "codebase visualizer", "repo map", "code structure"],
  },
  {
    title: "Landing Roaster",
    description: "Get a brutal, data-driven audit of your landing page's conversion killers.",
    href: "/tools/landing-page-roaster",
    icon: Flame,
    color: "text-orange-500",
    bg: "bg-orange-500/10",
    category: "Analysis",
    badge: "New",
    keywords: ["landing page audit", "website critique", "conversion optimization", "landing page feedback"],
  },
  {
    title: "HN Inspector",
    description: "Analyze the sentiment of the intellectual crowd on HackerNews.",
    href: "/tools/hackernews-inspector",
    icon: MessageSquare,
    color: "text-orange-500",
    bg: "bg-orange-500/10",
    category: "Analysis",
    badge: "Beta",
    keywords: ["hacker news analysis", "hn sentiment", "hacker news trends", "tech sentiment"],
  },
  {
    title: "Resume Roaster",
    description: "Get a brutal 6-second critique from a FAANG recruiter persona.",
    href: "/tools/resume-roaster",
    icon: FileSearch,
    color: "text-violet-500",
    bg: "bg-violet-500/10",
    category: "Analysis",
    badge: "New",
    keywords: ["resume review", "resume critique", "cv checker", "resume feedback"],
  },
  {
    title: "Viral Title Gen",
    description: "Generate YouTube titles backed by deep research.",
    href: "/tools/youtube-title-generator",
    icon: Youtube,
    color: "text-red-500",
    bg: "bg-red-500/10",
    category: "Marketing",
    keywords: ["youtube title generator", "viral titles", "video catchy titles", "youtube seo"],
  },
  {
    title: "Script Generator",
    description: "Generate engaging YouTube scripts from simple prompts.",
    href: "/tools/youtube-script-generator",
    icon: Video,
    color: "text-red-500",
    bg: "bg-red-500/10",
    category: "Marketing",
    keywords: ["youtube script generator", "video script writer", "ai script writer", "content creator tools"],
  },
  {
    title: "Email Subject Gen",
    description: "Create high-converting email subject lines instantly.",
    href: "/tools/email-subject-line-generator",
    icon: Mail,
    color: "text-blue-500",
    bg: "bg-blue-500/10",
    category: "Marketing",
    keywords: ["email subject generator", "subject line tester", "newsletter titles", "email marketing"],
  },
  {
    title: "Insta Caption Gen",
    description: "Generate engaging Instagram captions with hashtags.",
    href: "/tools/instagram-caption-generator",
    icon: Camera,
    color: "text-pink-500",
    bg: "bg-pink-500/10",
    category: "Social",
    keywords: ["instagram caption generator", "ig captions", "social media captions", "hashtag generator"],
  },
  {
    title: "Rynk Companion",
    description: "AI grammar and tone fixer in your browser.",
    href: "https://github.com/rynk-ai/rynk-companion",
    icon: Chrome,
    color: "text-sky-500",
    bg: "bg-sky-500/10",
    category: "Developer",
    badge: "Extension",
    keywords: ["chrome extension", "grammar extension", "ai writing assistant"],
  },
];
